name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install
    - run: yarn run jest
